name: Mirror to barabd (token_barabd)

on:
  push:
    branches: ['**']        # কেবল main চাইলে ['main']
  workflow_dispatch: {}     # ম্যানুয়ালি চালাতে পারবেন

concurrency:
  group: mirror-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Fetch all branches/tags
        run: |
          git remote set-branches --add origin '*'
          git fetch --all --tags --prune

      # আগে API দিয়ে টোকেনের অ্যাক্সেস সত্যি আছে কি না চেক
      - name: Verify token can see target repo
        env:
          MIRROR_TOKEN: ${{ secrets.token_barabd }}
        run: |
          set -e
          code=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${MIRROR_TOKEN}" \
            https://api.github.com/repos/barabd/school-management-system)
          echo "GitHub API HTTP $code"
          if [ "$code" != "200" ]; then
            echo "❌ Token cannot access barabd/school-management-system (private)."
            echo "➡️  Fix: regenerate Fine-grained (Contents: Read&Write, selected repo) or use Classic PAT with repo scope, then update secret token_barabd."
            exit 1
          fi

      - name: Configure mirror remote (idempotent, no scary errors)
        env:
          MIRROR_TOKEN: ${{ secrets.token_barabd }}
        run: |
          set -e
          git config --global user.email "mirror-bot@users.noreply.github.com"
          git config --global user.name  "Mirror Bot"
          URL="https://x-access-token:${MIRROR_TOKEN}@github.com/barabd/school-management-system.git"
          if git remote get-url mirror >/dev/null 2>&1; then
            git remote set-url mirror "$URL"
          else
            git remote add mirror "$URL"
          fi
          git remote -v
          git ls-remote --heads mirror

      # নিরাপদ সিঙ্ক (কিছু ডিলিট করে না)
      - name: Push branches
        run: git push mirror --all
      - name: Push tags
        run: git push mirror --tags

      # কড়া মিরর (সতর্কতা: ডিলিটসহ একদম হুবহু মিলিয়ে দেবে)
      # - name: Strict mirror
      #   run: git push --mirror mirror
