name: Mirror to barabd

on:
  push:
    branches: ['**']     # <-- mirror pushes from any branch (switch to ['main'] if you only want main)
  create:
    branches: ['**']
  delete:
    branches: ['**']

concurrency:
  group: mirror-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      # get all branches/tags from origin so we can push them on first run
      - name: Fetch all branches/tags
        run: |
          git remote set-branches --add origin '*'
          git fetch --all --tags --prune

      - name: Configure mirror remote (idempotent)
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          set -e
          git config --global user.email "mirror-bot@users.noreply.github.com"
          git config --global user.name  "Mirror Bot"

          URL="https://x-access-token:${MIRROR_TOKEN}@github.com/barabd/school-management-system.git"
          git remote set-url mirror "$URL" || git remote add mirror "$URL"
          git remote -v

      # SAFE: keeps target updated, doesn't delete anything
      - name: Push branches
        run: git push mirror --all

      - name: Push tags
        run: git push mirror --tags

      # STRICT (optional): exact mirror incl. deletions; uncomment instead of the two steps above
      # - name: Strict mirror (dangerous—overwrites target)
      #   run: git push --mirror mirror
