name: Mirror to barabd

on:
  push:
    branches:
      - '**'

jobs:
  mirror:
    if: ${{ github.repository == 'SaadSakib66/school-management-system' }}
    runs-on: ubuntu-latest
    env:
      MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - run: git config --global --unset-all http.https://github.com/.extraheader || true

      - run: |
          git config user.name "Mirror Bot"
          git config user.email "mirror@example.com"

      - name: Sanity: MIRROR_TOKEN present?
        run: |
          if [ -z "$MIRROR_TOKEN" ]; then echo "MIRROR_TOKEN missing"; exit 1; fi
          echo "MIRROR_TOKEN is set"

      - name: Push to mirror (force mirror all branches & tags)
        run: |
          set -euxo pipefail
          git remote remove mirror || true
          git remote add mirror https://barabd:${MIRROR_TOKEN}@github.com/barabd/school-management-system.git
          git push mirror --force --prune refs/heads/*:refs/heads/*
          git push mirror --force --prune --tags
