name: Mirror to barabd
on: push

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "Mirror Bot"
          git config user.email "mirror@example.com"

      - name: Push to mirror (HTTPS with PAT)
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          set -euxo pipefail
          git remote remove mirror || true
          git remote add mirror https://barabd:${TOKEN}@github.com/barabd/school-management-system.git
          # প্রথমবার সব ব্রাঞ্চ/ট্যাগ পাঠাই
          git push mirror --all
          git push mirror --tags
