name: Mirror to barabd
on: push

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history (no creds)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false   # ← GITHUB_TOKEN না রাখতে

      - name: Remove GitHub extraheader if any
        run: git config --global --unset-all http.https://github.com/.extraheader || true

      - name: Configure git
        run: |
          git config user.name "Mirror Bot"
          git config user.email "mirror@example.com"

      # চাইলে এই স্যানিটি চেক স্টেপ রাখুন
      - name: Sanity: MIRROR_TOKEN present?
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          if [ -z "$TOKEN" ]; then echo "❌ MIRROR_TOKEN missing"; exit 1; fi
          echo "✅ MIRROR_TOKEN is set"

      - name: Push to mirror (HTTPS with PAT)
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}   # barabd অ্যাকাউন্টের PAT
        run: |
          set -euxo pipefail
          git remote remove mirror || true
          git remote add mirror https://barabd:${TOKEN}@github.com/barabd/school-management-system.git
          git push mirror --all
          git push mirror --tags
