name: Mirror to barabd (token_barabd)

on:
  push:
    branches: ['**']        # কেবল main চাইলে: ['main']

concurrency:
  group: mirror-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      # সব ব্রাঞ্চ/ট্যাগ টেনে নিই যেন প্রথম রানেই পুরো ইতিহাস পুশ হয়
      - name: Fetch all branches/tags
        run: |
          git remote set-branches --add origin '*'
          git fetch --all --tags --prune

      - name: মিরর রিমোট কনফিগার (idempotent)
        env:
          MIRROR_TOKEN: ${{ secrets.token_barabd }}   # ← আপনার নতুন সিক্রেট নাম
        run: |
          set -e
          git config --global user.email "mirror-bot@users.noreply.github.com"
          git config --global user.name  "Mirror Bot"

          URL="https://x-access-token:${MIRROR_TOKEN}@github.com/barabd/school-management-system.git"
          git remote set-url mirror "$URL" || git remote add mirror "$URL"
          git remote -v
          git ls-remote --heads mirror   # দ্রুত অথ টেস্ট

      # নিরাপদ মোড: টার্গেটে কিছু ডিলিট করে না
      - name: Push branches
        run: git push mirror --all

      - name: Push tags
        run: git push mirror --tags

      # কড়া মিরর (সাবধান): টার্গেটকে একদম সোর্সের মতো বানাবে, ডিলিটসহ
      # - name: Strict mirror
      #   run: git push --mirror mirror
